title: Bike Index stolen bike widget
description: > #
  A Bike Index widget for every occassion.
  Show the stolen bikes, find the stolen bikes, get them back!
baseurl: 
url: https://widget.bikeindex.org
safe: false
twitter_username: bikeindex
github_username:  bikeindex
sass:
  style: :compressed
exclude:
  - divshot.json
  - Gemfile
  - Gemfile.lock
  - README.markdown
  - readme_example.png
asset_pipeline:
  bundle: true
  compress: true
  output_path: /
  display_path: nil      
  gzip: false       